export const auditActionLabels: Record<string, string> = {
  student_created: "Talebe oluşturuldu",
  student_updated: "Talebe bilgileri güncellendi",
  student_status_changed: "Talebe durumu değiştirildi",
  student_class_changed: "Talebe sınıfı değiştirildi",
  grade_saved: "Not girildi/güncellendi",
  evaluation_saved: "Kanaat girildi/güncellendi",
  infirmary_record_saved: "Revir kaydı oluşturuldu/güncellendi",
  document_saved: "Evrak eklendi/güncellendi",
  parent_created: "Veli oluşturuldu",
  parent_student_linked: "Veli talebeye bağlandı",
  parent_student_unlinked: "Veli talebeden bağ kaldırıldı",
  staff_profile_created: "Hoca/kullanıcı oluşturuldu",
  auth_account_created: "Auth hesabı oluşturuldu",
  auth_password_reset: "Geçici şifre atandı",
  password_reset_by_admin: "Şifre yönetici tarafından sıfırlandı",
  class_course_created: "Sınıfa ders atandı",
  class_course_updated: "Derse hoca atandı",
  schedule_slot_created: "Ders programı slotu oluşturuldu",
  schedule_slot_updated: "Ders programı slotu güncellendi",
  dormitory_created: "Yatakhane oluşturuldu",
  dormitory_updated: "Yatakhane güncellendi",
  dormitory_assignment_created: "Talebe yerleştirildi",
  dormitory_assignment_ended: "Yerleşim sonlandırıldı",
  library_book_created: "Kitap eklendi",
  library_book_updated: "Kitap güncellendi",
  library_loan_created: "Emanet verildi",
  library_loan_returned: "Emanet teslim alındı",
  library_loan_lost: "Emanet kayıp işaretlendi",
  library_document_uploaded: "Doküman yüklendi",
  library_category_created: "Kategori oluşturuldu",
  library_category_updated: "Kategori güncellendi",
  guidance_interview_created: "Rehberlik görüşmesi oluşturuldu",
  guidance_interview_updated: "Rehberlik görüşmesi güncellendi",
  guidance_follow_up_created: "Takip planı oluşturuldu",
  guidance_follow_up_completed: "Takip tamamlandı",
  guidance_follow_up_cancelled: "Takip iptal edildi",
  guidance_survey_created: "Anket oluşturuldu",
  guidance_survey_closed: "Anket kapatıldı",
  guidance_activity_created: "Etkinlik oluşturuldu",
  guidance_activity_updated: "Etkinlik güncellendi",
  guidance_activity_completed: "Etkinlik tamamlandı",
  announcement_created: "Duyuru oluşturuldu",
  announcement_updated: "Duyuru güncellendi",
  assistant_question_asked: "Nizam Aİ sorgusu yapıldı",
  assistant_history_cleared: "Nizam Aİ sohbet geçmişi silindi",
  term_created: "Dönem oluşturuldu",
  term_activated: "Dönem aktif edildi",
  term_viewed: "Dönem görüntülendi",
  term_updated: "Dönem güncellendi",
  term_closed: "Dönem kapatıldı",
  term_snapshot_created: "Dönem snapshot'ı oluşturuldu",
  term_closure_failed: "Dönem sonlandırma başarısız",
  term_closure_completed: "Dönem sonlandırma tamamlandı",
  archive_export_created: "Arşiv export oluşturuldu",
  archive_export_downloaded: "Arşiv export indirildi",
  archive_export_failed: "Arşiv export başarısız",
};

export const auditActionOptions = [
  { value: "", label: "Tümü" },
  ...Object.entries(auditActionLabels).map(([value, label]) => ({ value, label })),
];

export const auditEntityTypeLabels: Record<string, string> = {
  student: "Talebe",
  grade: "Not",
  evaluation: "Kanaat",
  infirmary_record: "Revir",
  document: "Evrak",
  parent: "Veli",
  parent_student_link: "Veli Bağı",
  staff_profile: "Kullanıcı",
  auth_account: "Auth Hesabı",
  class_course: "Ders Ataması",
  weekly_schedule_slot: "Ders Programı",
  dormitory: "Yatakhane",
  dormitory_assignment: "Yerleşim",
  library_book: "Kitap",
  library_loan: "Emanet",
  library_document: "Kütüphane Dokümanı",
  library_category: "Kategori",
  guidance_interview: "Rehberlik Görüşmesi",
  guidance_follow_up: "Takip Planı",
  guidance_survey: "Anket",
  guidance_activity: "Etkinlik",
  guidance_activity_participant: "Etkinlik Katılımcısı",
  announcement: "Duyuru",
  assistant: "Nizam Aİ",
  academic_term: "Akademik Dönem",
  term_closure_run: "Dönem Kapanış Operasyonu",
  archive_export: "Arşiv Export",
};

export const auditEntityTypeOptions = [
  { value: "", label: "Tümü" },
  ...Object.entries(auditEntityTypeLabels).map(([value, label]) => ({ value, label })),
];
